### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by omsmith** [nolanlawson/sublevel-pouchdb#2]
Hey @nolanlawson, running into the missing _inherits_ when using a modular pouch 5.4 build. Think this could get a release that can be picked up for the next pouchdb?

**Comment by nolanlawson** [comment]
That's really weird – it looks like that's covered [in this line](https://github.com/pouchdb/sublevel-pouchdb/blob/ac9f950cc0776c38767609927c77f8d10f4d3cc9/package.json#L13). Do you have steps to reproduce?

**Comment by nolanlawson** [comment]
Oh shoot yeah, it wasn't published. Crap. OK, will do, but it will also require a new pouchdb release as well.

**Comment by nolanlawson** [comment]
1.0.1 published

**Comment by omsmith** [comment]
Thanks @nolanlawson
